# JPA Configuration
spring:
  jpa:
    hibernate:
      ddl-auto: ${mysql.ddl.setting}
    properties:
      hibernate:
        format_sql: true
  profiles:
    include:
      - db
      - oauth
      - redis
      - jwt
  # db 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
  # 1:1 채팅을 위한 Redis 설정
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
#      password: ${redis.password}
  jwt:
    secret-key: ${jwt.secret-key}

oauth:
  kakao:
    client-id: ${kakao.client-id}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: ${naver.secret}
    client-id: ${naver.client-id}
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

# Hibernate SQL Debugging
logging:
  level:
    org:
      hibernate:
        sql: debug