server:
  port: 8081

# JPA Configuration
spring:
  jpa:
    hibernate:
      ddl-auto: ${MARIA_DDL_SETTING}
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
  profiles:
    include:
      - db
      - oauth
      - redis
      - jwt
      - openvidu
  # db 설정
  datasource:
    driver-class-name: ${MARIA_DRIVER}
    url: ${MARIA_URL}
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 2
      max-lifetime: 240000
      maximum-pool-size: 2
  # 1:1 채팅을 위한 Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
#      password: ${redis.password}
  jwt:
    secret-key: ${JWT_SECRET_KEY}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: ${NAVER_SECRET}
    client-id: ${NAVER_CLIENT_ID}
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

# Hibernate SQL Debugging
logging:
  level:
    org:
      hibernate:
        sql: debug

# OpenVidu
OPENVIDU_URL: ${OPENVIDU_URL}
OPENVIDU_SECRET: ${OPENVIDU_SECRET}