server:
  port: 8081

# JPA Configuration
spring:
  jpa:
    hibernate:
      ddl-auto: ${maria.ddl.setting}
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
  profiles:
    include:
      - db
      - oauth
      - redis
      - jwt
      - openvidu
  # db 설정
  datasource:
    driver-class-name: ${maria.driver}
    url: ${maria.url}
    username: ${maria.username}
    password: ${maria.password}
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 2
      max-lifetime: 240000
      maximum-pool-size: 2
  # 1:1 채팅을 위한 Redis 설정
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
#      password: ${redis.password}
  jwt:
    secret-key: ${jwt.secret-key}

oauth:
  kakao:
    client-id: ${kakao.client-id}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: ${naver.secret}
    client-id: ${naver.client-id}
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

# Hibernate SQL Debugging
logging:
  level:
    org:
      hibernate:
        sql: debug

# OpenVidu
OPENVIDU_URL: ${openvidu.url}
OPENVIDU_SECRET: ${openvidu.secret}