server:
  port: 8081

whitelist: ${WHITELIST}

spring:
  jpa:
    hibernate:
      ddl-auto: ${MARIA_DDL_SETTING}
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
  profiles:
    include:
      - db
      - oauth
      - redis
      - jwt
      - openvidu
      - springdoc
  datasource:
    driver-class-name: ${MARIA_DRIVER}
    url: ${MARIA_URL}
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 2
      max-lifetime: 240000
      maximum-pool-size: 2
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jwt:
    secret-key: ${JWT_SECRET_KEY}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: ${NAVER_SECRET}
    client-id: ${NAVER_CLIENT_ID}
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

openvidu:
  url: ${OPENVIDU_URL}
  secret: ${OPENVIDU_SECRET}

springdoc:
  api-docs:
    enabled: true
    path: ${API_DOCS_PATH}
  swagger-ui:
    path: ${SWAGGER_UI_PATH}
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    info:
      title: CMIUC API Server
      description: CMIUC
      version: 0.0.1